# Generated by Django 2.1.7 on 2019-03-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190313_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dressing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Dress')),
            ],
        ),
        migrations.CreateModel(
            name='Outfitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressing_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Dressing')),
                ('matron_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Matron')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('more', models.TextField(blank=True, max_length=1000, null=True)),
                ('shoeURL', models.URLField(blank=True, null=True)),
                ('shoed_on', models.ManyToManyField(related_name='shoe_id', through='core.Outfitting', to='core.Dressing')),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.RenameModel(
            old_name='Resemblance',
            new_name='Collecting',
        ),
        migrations.RenameModel(
            old_name='Membership',
            new_name='Stringing',
        ),
        migrations.RemoveField(
            model_name='bead',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='bead',
            name='strung_with',
        ),
        migrations.RemoveField(
            model_name='bowl',
            name='collecting',
        ),
        migrations.RemoveField(
            model_name='necklace',
            name='stringing',
        ),
        migrations.AddField(
            model_name='bead',
            name='collected_to',
            field=models.ManyToManyField(related_name='bead_id', through='core.Collecting', to='core.Bowl'),
        ),
        migrations.AddField(
            model_name='bead',
            name='strung_to',
            field=models.ManyToManyField(related_name='bead_id', through='core.Stringing', to='core.Necklace'),
        ),
        migrations.AddField(
            model_name='bowl',
            name='collecting_with',
            field=models.ManyToManyField(related_name='bowl_id', through='core.Collecting', to='core.Bead'),
        ),
        migrations.AddField(
            model_name='necklace',
            name='stringing_with',
            field=models.ManyToManyField(related_name='necklace_id', through='core.Stringing', to='core.Bead'),
        ),
        migrations.AddField(
            model_name='outfitting',
            name='shoe_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Shoe'),
        ),
        migrations.AddField(
            model_name='dressing',
            name='dressed_with',
            field=models.ManyToManyField(related_name='dressing_id', through='core.Outfitting', to='core.Shoe'),
        ),
        migrations.AddField(
            model_name='dressing',
            name='matron_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Matron'),
        ),
        migrations.AddField(
            model_name='dress',
            name='dressed_on',
            field=models.ManyToManyField(related_name='dress_id', through='core.Dressing', to='core.Matron'),
        ),
        migrations.AddField(
            model_name='matron',
            name='dressing_with',
            field=models.ManyToManyField(related_name='matron_id', through='core.Dressing', to='core.Dress'),
        ),
        migrations.AddField(
            model_name='matron',
            name='outfitting_with',
            field=models.ManyToManyField(related_name='matron_id', through='core.Outfitting', to='core.Shoe'),
        ),
    ]
