# Generated by Django 2.1.7 on 2019-03-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190317_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('meeting_on', models.DateField(auto_now_add=True, null=True)),
                ('meeting_start_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('meeting_end_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('meeting_type', models.CharField(max_length=100)),
                ('meetupURL', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-meeting_on'],
            },
        ),
    ]
