# Generated by Django 2.1.7 on 2019-03-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190317_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dress',
            options={'ordering': ['order_by_help']},
        ),
        migrations.AddField(
            model_name='dress',
            name='order_by_help',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
